# Generated by Django 5.1 on 2024-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
