# Generated by Django 5.1 on 2024-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_zip_code_ordermodel_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_shiped',
            field=models.BooleanField(default=False),
        ),
    ]
